Name=input("Enter your name: ")
studentId=input("Enter your id: ")
Department=input("Enter your department: ")
year=int(input("Enter your year: "))
University=input("Enter your university: ")
phone=int(input("Enter your phone number: "))
print("-"*35)
print("|""    AKIBA STUDENT CARD            ""|")
print("-"*35)
print(f"| Name: {Name}           |")
print(f"| ID: {studentId}                  |")
print(f"| Department: {Department}             |")
print(f"| Year: {year}                          |")
print(f"| University: {University}                  |")
print(f"| phone: {phone}                 |")
print("-"*35)
