name=input("what is your name?: ")
python=float(input("what is your python score out of 100 ?: "))
english=float(input("what is your english score out of 100 ?: "))
mathematics=float(input("what is your mathematics result ourt of 100 ?"))
Average=(python+english+mathematics)/3
print("="*45)
print("        STUDENT RESULT")
print("="*45)
print(f"Student: {name}")
print(f"Python: {python}")
print(f"English: {english}")
print(f"Mathematics: {mathematics}")
print("-"*30)
print(f"Average: {Average}")
print("="*45)