name=input("what is your name? :  ")
weight=float(input("what  is your weight in kilograms?: "))
height=float(input("what is your height in meters?: "))
bmi=weight/(height**2)
print("="*35)
print("      BMI REPORT")
print("="*35)
print(f" Name: {name}")
print(f" Weight: {weight}")
print(f" Height: {height}")
print(f" BMI: {bmi:.2f}")
print("="*35)