name=input("what is ur name?: ")
product1=input("write the name of first product u buy: " )
quantity1=int(input("write the quantity of the first product in Kg: "))
product2=input("write the name of the second product: ")
quantity2=int(input("write the quantity of the second product in kg: "))
price1=float(input("what is the price of the first product? in birr: "))
price2=float(input("what is the price of the second product? in birr: "))
total=(quantity1*price1)+(quantity2*price2)
print("="*45)
print("        RECEIPT")
print("="*45)
print(f"Customer: {name}")
print("Product      price      Qty")
print("-"*30)
print(f"{product1}    {price1}     {quantity1}")
print(f"{product2}    {price2}    {quantity2}")
print(f" Total: {total}")
print("Thank you for shopping!")
print("="*45)
