name=input("what is your name?: ")
basic=float(input('what is your  basic salary? in ETB: '))
transport=float(input("what is your transport allowance?in ETB: "))
food=float(input("what is your food allowance? in ETB: "))
Gross=(basic+transport+food)
print("="*45)
print("     EMPLOYEE PAYSLIP")
print("="*45)
print(f"Employee: {name}")
print(f"Basic Salary: {basic}")
print(f"Transport Allowance: {transport}")
print(f"Food Allowance:  {food}")
print("-"*30)
print(f"Gross Salary:  {Gross}")
print("="*45)