first_name=input(" Enter your first name: ")
last_name=input("Enter your last name: ")
fullname= first_name+last_name
age=int(input("Enter your age: "))
student_id=input("Enter your id: ")
city=input("Enter your city: ")
university=input(" Enter your university: ")
department=input(" Enter your department: ")
email=input("Enter your email: ")
phone_number=input("enter your phone number: ")
programming_language=input("enter your favorite programming language: ")
programming_goal=input("enter your programming goal: ")
print("="*55)
print("          AKIBA STUDENT PROFILE")
print("="*55)
print("                              ")
print(f"Name: {fullname}")
print(f"Student ID: {student_id}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"University: {university}")
print(f"Department: {department}")
print(f"Email: {email}")
print(f"Phone: {phone_number}")
print(f"Favorite Language: {programming_language}")
print("                                              ")
print(f"Programming Goal:")
print(programming_goal)
print("="*55)